# Snapshot baseline tests - Generated by r-package-cleanup
# Purpose: Verify all exported functions exist and are callable
# Date: 2026-01-30

test_that("all exported functions exist and are functions", {
  exports <- getNamespaceExports("bertopic")
  
  for (fn_name in exports) {
    fn <- tryCatch(
      get(fn_name, envir = asNamespace("bertopic")),
      error = function(e) NULL
    )
    expect_true(!is.null(fn), 
      info = paste("Export", fn_name, "should exist"))
  }
})

test_that("core bertopic functions are exported", {
  core_fns <- c(
    "bert_topic", "bert_fit", "bert_fit_transform", "bert_transform",
    "bert_topic_info", "bert_topic_keywords", "bert_save", "bert_load",
    "import_bertopic", "sentence_transformer"
  )
  
  exports <- getNamespaceExports("bertopic")
  
  for (fn in core_fns) {
    expect_true(fn %in% exports, 
      info = paste(fn, "should be exported"))
  }
})

test_that("import functions are exported", {
  import_fns <- c(
    "import_bertopic", "import_keybert", "import_polyfuzz",
    "import_sklearn", "import_umap", "import_sentence_transformers"
  )
  
  exports <- getNamespaceExports("bertopic")
  
  for (fn in import_fns) {
    expect_true(fn %in% exports,
      info = paste(fn, "should be exported"))
  }
})

test_that("tbl_* utility functions are exported", {
  tbl_fns <- grep("^tbl_", getNamespaceExports("bertopic"), value = TRUE)
  expect_true(length(tbl_fns) > 0)
})

test_that("extract_* functions are exported", {
  extract_fns <- grep("^extract_", getNamespaceExports("bertopic"), value = TRUE)
  expect_true(length(extract_fns) > 0)
})

test_that("keybert functions are exported", {
  kb_fns <- grep("keybert", getNamespaceExports("bertopic"), value = TRUE)
  expect_true(length(kb_fns) > 0)
})

test_that("polyfuzz functions are exported", {
  pf_fns <- grep("polyfuzz", getNamespaceExports("bertopic"), value = TRUE)
  expect_true(length(pf_fns) > 0)
})

test_that("representation model functions are exported", {
  rep_fns <- grep("representation", getNamespaceExports("bertopic"), value = TRUE)
  expect_true(length(rep_fns) > 0)
})

test_that("embedding functions are exported", {
  embed_fns <- c("sentence_transformer", "flair_embeddings")
  exports <- getNamespaceExports("bertopic")
  
  for (fn in embed_fns) {
    expect_true(fn %in% exports,
      info = paste(fn, "should be exported"))
  }
})

test_that("export count matches expected range", {
  exports <- getNamespaceExports("bertopic")
  # Baseline: 135 exports as of 2026-01-30
  expect_true(length(exports) > 100)
  expect_true(length(exports) < 200)
})

# Additional structural tests

test_that("package imports reticulate correctly", {
  # Verify reticulate is a dependency via the loaded namespace
  imports <- getNamespaceImports("bertopic")
  expect_true("reticulate" %in% names(imports))
})

test_that("package info is correct", {
  pkg_info <- packageDescription("bertopic")
  expect_equal(pkg_info$Package, "bertopic")
  expect_true(!is.null(pkg_info$Version))
  expect_true(grepl("reticulate", pkg_info$Imports))
})

test_that("all bert_* functions have consistent prefix", {
  bert_fns <- grep("^bert_", getNamespaceExports("bertopic"), value = TRUE)
  expect_gt(length(bert_fns), 20)
  # All should be functions
  for (fn in bert_fns[1:5]) {  # Sample check
    expect_true(is.function(get(fn, envir = asNamespace("bertopic"))))
  }
})

test_that("all import_* functions have consistent prefix", {
  import_fns <- grep("^import_", getNamespaceExports("bertopic"), value = TRUE)
  expect_gt(length(import_fns), 5)
})

test_that("tbl_* functions are properly exported", {
  tbl_fns <- grep("^tbl_", getNamespaceExports("bertopic"), value = TRUE)
  expect_gt(length(tbl_fns), 5)
})

test_that("package has expected function categories", {
  exports <- getNamespaceExports("bertopic")
  
  # Check major categories exist
  bert_count <- sum(grepl("^bert_", exports))
  import_count <- sum(grepl("^import_", exports))
  tbl_count <- sum(grepl("^tbl_", exports))
  keybert_count <- sum(grepl("keybert", exports))
  polyfuzz_count <- sum(grepl("polyfuzz", exports))
  
  expect_gt(bert_count, 15)
  expect_gt(import_count, 5)
  expect_gt(tbl_count, 3)
  expect_gt(keybert_count, 3)
  expect_gt(polyfuzz_count, 3)
})
